name = "ctrl-build"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "ctrl-build"

[env.preview]
name = "ctrl-build-preview"

[build]
command = "npm run build"
cwd = "."


